apps/ecommerce/urls.py
from django.urls import path

from . import views

app_name = "ecommerce"

urlpatterns = [
    path("", views.ecommerce_home, name="ecommerce_home"),
    path("products/<slug:product_id>/purchase/", views.purchase_product, name="purchase_product"),
    path("products/<slug:product_id>/purchase/success/", views.checkout_success, name="checkout_success"),
    path("products/<slug:product_id>/purchase/cancel/", views.checkout_cancelled, name="checkout_cancelled"),
    path("purchases", views.purchases, name="purchases"),
]

my_saas_app/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.urls import path, include
from django.views.generic import RedirectView
from django.views.i18n import JavaScriptCatalog
from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView, SpectacularRedocView

from wagtail.admin import urls as wagtailadmin_urls
from wagtail import urls as wagtail_urls
from wagtail.api.v2.views import PagesAPIViewSet
from wagtail.contrib.sitemaps import Sitemap
from wagtail.documents import urls as wagtaildocs_urls
from apps.web.sitemaps import StaticViewSitemap

PagesAPIViewSet.schema = None  # hacky workaround for https://github.com/wagtail/wagtail/issues/8583

sitemaps = {
    "static": StaticViewSitemap(),
    "wagtail": Sitemap(),
}

urlpatterns = [
    # redirect Django admin login to main login page
    path("admin/login/", RedirectView.as_view(pattern_name="account_login")),
    path("admin/", admin.site.urls),
    path("dashboard/", include("apps.dashboard.urls")),
    path("i18n/", include("django.conf.urls.i18n")),
    path("jsi18n/", JavaScriptCatalog.as_view(), name="javascript-catalog"),
    path("sitemap.xml", sitemap, {"sitemaps": sitemaps}, name="django.contrib.sitemaps.views.sitemap"),
    path("accounts/", include("allauth.urls")),
    path("users/", include("apps.users.urls")),
    path("ecommerce/", include("apps.ecommerce.urls")),
    path("", include("apps.web.urls")),
    path("pegasus/", include("pegasus.apps.examples.urls")),
    path("pegasus/employees/", include("pegasus.apps.employees.urls")),
    path("group-chat/", include("apps.group_chat.urls")),
    path("chat/", include("apps.chat.urls")),
    path("ai-images/", include("apps.ai_images.urls")),
    path("support/", include("apps.support.urls")),
    path("celery-progress/", include("celery_progress.urls")),
    # API docs
    path("api/schema/", SpectacularAPIView.as_view(), name="schema"),
    # Optional UI - you may wish to remove one of these depending on your preference
    path("api/schema/swagger-ui/", SpectacularSwaggerView.as_view(url_name="schema"), name="swagger-ui"),
    path("api/schema/redoc/", SpectacularRedocView.as_view(url_name="schema"), name="redoc"),
    # djstripe urls - for webhooks
    path("stripe/", include("djstripe.urls", namespace="djstripe")),
    # hijack urls for impersonation
    path("hijack/", include("hijack.urls", namespace="hijack")),
    # wagtail config
    # redirect Wagtail admin login to main login page
    path("cms/login/", RedirectView.as_view(pattern_name="account_login")),
    path("cms/", include(wagtailadmin_urls)),
    path("documents/", include(wagtaildocs_urls)),
    path("content/", include(wagtail_urls)),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/ecommerce/models.py
from django.conf import settings
from django.db import models
from djstripe.models import Price, Product

from apps.utils.models import BaseModel


class Purchase(BaseModel):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    price = models.ForeignKey(Price, on_delete=models.CASCADE)
    checkout_session_id = models.CharField(max_length=100, unique=True, db_index=True)
    is_valid = models.BooleanField(default=True)

apps/ecommerce/views.py
from django.conf import settings
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404
from django.template.response import TemplateResponse
from django.urls import reverse
from django.utils.translation import gettext as _
from djstripe.models import Product

from apps.utils.billing import get_stripe_module
from apps.web.meta import absolute_url

from .helpers import create_purchase_from_checkout_session
from .models import Purchase


@login_required
def ecommerce_home(request):
    products = Product.objects.filter(active=True, id__in=settings.ACTIVE_ECOMMERCE_PRODUCT_IDS).select_related(
        "default_price"
    )
    return TemplateResponse(
        request,
        "ecommerce/ecommerce_home.html",
        {
            "active_tab": "ecommerce",
            "products": products,
        },
    )


@login_required
def purchase_product(request, product_id: str):
    product = get_object_or_404(Product, id=product_id)
    stripe = get_stripe_module()
    success_url = absolute_url(reverse("ecommerce:checkout_success", args=[product_id]))
    cancel_url = absolute_url(reverse("ecommerce:checkout_cancelled", args=[product_id]))
    customer_kwargs = {}
    if request.user.customer:
        customer_kwargs["customer"] = request.user.customer.id
    else:
        customer_kwargs["customer_email"] = request.user.email
        # create a customer object so we can re-use it in future payments
        customer_kwargs["customer_creation"] = "always"

    checkout_session = stripe.checkout.Session.create(
        success_url=success_url + "?session_id={CHECKOUT_SESSION_ID}",
        cancel_url=cancel_url,
        payment_method_types=["card"],
        client_reference_id=request.user.id,
        mode="payment" if not product.default_price.recurring else "subscription",
        line_items=[
            {
                "price": product.default_price.id,
                "quantity": 1,
            },
        ],
        allow_promotion_codes=True,
        metadata={
            "source": "ecommerce",  # used by the webhook to only process checkouts from here
        },
        **customer_kwargs,
    )
    return HttpResponseRedirect(checkout_session.url)


@login_required
def checkout_success(request, product_id: str):
    # handle fulfillment
    product = get_object_or_404(Product, id=product_id)
    session_id = request.GET.get("session_id")
    session = get_stripe_module().checkout.Session.retrieve(session_id, expand=["line_items"])
    client_reference_id = int(session.client_reference_id)
    assert client_reference_id == request.user.id
    create_purchase_from_checkout_session(session)
    messages.success(
        request,
        _("Your purchase of {product_name} was successful. Thanks for the support!").format(product_name=product.name),
    )
    return HttpResponseRedirect(reverse("ecommerce:ecommerce_home"))


@login_required
def checkout_cancelled(request, product_id: str):
    product = get_object_or_404(Product, id=product_id)
    messages.info(request, _("Your purchase of {product_name} was cancelled.").format(product_name=product.name))
    return HttpResponseRedirect(reverse("ecommerce:ecommerce_home"))


@login_required
def purchases(request):
    purchases = Purchase.objects.filter(user=request.user)
    return TemplateResponse(
        request,
        "ecommerce/purchases.html",
        {
            "active_tab": "ecommerce",
            "purchases": purchases,
        },
    )

templates/ecommerce/components/product_card.html
{% load static %}
{% load i18n %}
<div class="pg-card h-100">
  <div class="pg-card-image">
    <figure class="image pg-ratio-3x2">
      <img class="img-fluid" src="{% if product.images %}{{ product.images.0 }}{% else %}{% static 'images/undraw/undraw_happy_birthday.svg' %}{% endif %}" alt="{{ product.name }}">
    </figure>
  </div>
  <div class="pg-card-body mt-2" style="display: flex; flex-direction: column; justify-content: space-between;">
    <div>
      <h3 class="pg-title">{{ product.name }}</h3>
      <p class="pg-subtitle">
        {{ product.description }}
      </p>
    </div>
    <div style="display: flex; justify-content: space-between; align-items: baseline;">
      {% if product.default_price %}
      <div class="mt-2">{{ product.default_price.human_readable_price }}</div>
      <a href="{% url 'ecommerce:purchase_product' product.id %}" class="pg-button-secondary" style="white-space: nowrap;">
        <span>Buy</span>
        <span class="pg-icon">
          <i class="fa fa-angle-double-right"></i>
        </span>
      </a>
      {% else %}
        <div class="mt-2">
          {% translate "This product does not yet have a price and is so unavailable for purchase." %}
        </div>
      {% endif %}
    </div>
  </div>
</div>

templates/ecommerce/components/products_empty.html
{% load static %}
{% load i18n %}
<h2 class="pg-subtitle">{% translate "No Products Available!" %}</h2>
<p class="mt-2">
  If you are setting this project up for the first time, be sure to set up your products in Stripe,
  run <code>./manage.py djstripe_sync_models price</code>,
  and set the <code>ACTIVE_ECOMMERCE_PRODUCT_IDS</code> in your settings/environment file.
  For more information, see the <a class="pg-link" href="https://docs.saaspegasus.com/payments">E-Commerce documentation</a>.
</p>

templates/ecommerce/components/purchases_empty.html
{% load static %}
{% load i18n %}
<div class="pg-columns">
  <div class="pg-column-one-third">
    <img class="img-fluid" alt="{% translate 'Nothing Here' %}" src="{% static 'images/undraw/undraw_empty.svg' %}">
  </div>
  <div class="pg-column">
    <h1 class="pg-title">{% translate "No Purchases" %}</h1>
    <h2 class="pg-subtitle">{% translate "When you buy a product from the store it will show up here." %}</h2>
    <p>
      <a class="pg-button-primary" href="{% url 'ecommerce:ecommerce_home' %}">
        <span>{% translate "View Store" %}</span>
      </a>
    </p>
  </div>
</div>